apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: argocd
spec:
  project: default
  destination:
    namespace: helm-app
    server: "https://kubernetes.default.svc"
  source:
    path: helm-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true