apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kustomize-guestbook
  namespace: argocd

spec:
  project: default
  destination:
    namespace: kustomize-guestbook
    server: "https://kubernetes.default.svc"
  source:
    path: kustomize-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps"
    targetRevision: master
    kustomize:
      namePrefix: staging-
      commonLabels:
        app: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
