apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ns-1-namebook
  namespace: argocd

spec:
  project: dev-project
  destination:
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  source:
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps"
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true # Deletes resources automatically
    syncOptions:
      - CreateNamespace=true
