apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-project-kustomize-guestbook
  namespace: argocd

spec:
  project: dev-project
  destination:
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  source:
    path: kustomize-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps"
    targetRevision: master
    kustomize:
      namePrefix: dev-
  syncPolicy:
    syncOptions:
      - CreateNamespace=true